---
- name: Hello World!
  hosts: switches
  connection: local
  gather_facts: false

  vars_prompt:
    - name: USERNAME
      prompt: User name
      private: false
    - name: DEVICE_PASSWORD
      prompt: Device password
      private: true

  tasks:
    - name: Get Junos device information
      juniper.device.facts:
        user: "{{ USERNAME }}"
        passwd: "{{ DEVICE_PASSWORD }}"
      register: junos_facts

    - name: Print Junos facts
      ansible.builtin.debug:
        msg: "{{ junos_facts }}"
