---
- name: Hello World!
  hosts : switches
  connection: local
  gather_facts: no

  vars_prompt:
    - name: USERNAME
      prompt: User name
      private: no
    - name: DEVICE_PASSWORD
      prompt: Device password
      private: yes

  tasks:
    - name: Get Junos device information
      juniper.device.facts:
        user: "{{ USERNAME }}"
        passwd: "{{ DEVICE_PASSWORD }}"
      register: junos_facts

    - name: Print Junos facts
      debug:
       msg: "{{ junos_facts }}"

