---
- name: 'Testing junos.device collection'
  hosts: junos
  connection: local
  gather_facts: false

#  The following lines are required only if ssh keys are not set up in both the controller machine and the host
#  vars_prompt:
#    - name: USERNAME
#      prompt: User name
#      private: false
#    - name: DEVICE_PASSWORD
#      prompt: Device password
#      private: true

  tasks:
    - name: Change hostname using private config mode.
      juniper.device.config:
#        The following lines are required only if ssh keys are not set up in both the controller machine and the host
#        user: "{{ USERNAME }}"
#        passwd: "{{ DEVICE_PASSWORD }}"
        timeout: 120
        config_mode: 'private'
        load: 'merge'
        lines:
          - "set system host-name {{ newhostname }}.test10"
        comment: "Ansible Ruben Testing: Change hostname"
      vars:
        output: 
      register: response


    - name: Print the config changes.
      when: response is changed
      debug:
        var: response.diff_lines

    - name: Change NTP servers using private config mode.
      juniper.device.config:
#        The following lines are required only if ssh keys are not set up in both the controller machine and the host
#        user: "{{ USERNAME }}"
#        passwd: "{{ DEVICE_PASSWORD }}"
        timeout: 120
        config_mode: 'private'
        load: 'merge'
        lines:
          - "set system ntp server {{ ntp_server1 }} prefer"
          - "set system ntp server {{ ntp_server2 }} prefer"
          - "set system ntp source-address {{ ntp_source_address }}"
        comment: "Ansible Ruben Testing: Change NTP servers"
      register: response


    - name: Print the config changes.
      when: response is changed
      debug:
        var: response.diff_lines
